typography_spectrum: 0.7542794535402209
content_rating:
  adult: false
color:
  brandStrength: 0.7707823847886175
  lightness: 0.14033668208867311
  saturation: 0.45361045305617154
  rhythmicContrast: 0.4109635928180069
  brandColors:
    - '#010715'
    - '#FFFEAB'
    - '#BF7351'
    - '#9C3C28'
    - '#053A38'
layout_spectrum: 0.8662041672505438
author:
  name: REBELiGAN
  email: REBELiGAN@gmail.com
  url: 'https://www.youtube.com/channel/UCCiLT6YyDPjOQoWgjvDIJHw'
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5eba1c38-ddc7-4924-906d-87bafcc86cef.jpg
name: REBELiGAN
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e67fb749-c103-4080-8d3a-d5b8fc11c820.jpg
title: 'Oh, sh**! It''s REBELiGAN.'
description: 'Oh, sh**, it''s...'
